import argparse
import hashlib
import os
from pathlib import Path
import re
import struct
import subprocess
import sys
import time

# Ensure UTF-8 output on any console (the script prints the U+2713 checkmark).
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")
    sys.stderr.reconfigure(encoding="utf-8")

import serial


REQUEST_HASH = 0x48
REQUEST_CHAIN = 0x43
REQUEST_VERIFY = 0x56
REQUEST_SIGN_TEST = 0x53
REQUEST_KEYGEN_TEST = 0x4B
REQUEST_LMOTS_KEYGEN_TEST = 0x60
REQUEST_LMOTS_SIGN_TEST = 0x61
REQUEST_LMOTS_VERIFY_TEST = 0x62
REQUEST_SEED_LOAD_TEST = 0x63
RESPONSE = 0x52
RESPONSE_SIZE = 48
VERIFY_VECTOR = Path("build/lms_verify_vector.txt")
VECTOR_OVERRIDE = None  # --vector specifies the vector file (e.g., 1KB large-message vector)
BIG_MSG = False  # Large message (>74B): message hash goes through HASH_ONCE_RAM, hw cycles change -> expectation relaxed

# Hash under test (selected via --hash). SHA-256 is the historical default; SHAKE256
# expected cycles come from Verilator SoC regression measurements (same RTL, board should match item by item).
HASH_MODE = "sha256"
# Pure-software baseline (--pure-software): LM-OTS/LMS bypass the hardware accelerator (LMS_FW_NO_HW_ACCEL),
# expected hw cycles=0, hits do not increase. HASH_ONCE/CHAIN protocol smoke tests still use hardware (RTL unchanged), expectations unchanged.
PURE_SW = False
# DERIVE_SHUFFLE=1 build (--shuffle, TVLA variant): batch tasks get random start shifts that offset
# DERIVE-segment cycle counts (measured verify +48, sign ±9% variation) -> skip precise cycle assertions (correctness still checked byte by byte).
# Compatibility: env var LMS_KAT_SKIP_CYCLES=1 is equivalent.
SHUFFLE = False
# Multi-parameter set (t8): parameter set under test. W=LM-OTS Winternitz w (1/2/4/8), H=LMS tree height (5/10/15).
# Vector file build/vectors/lms_verify_vector_W{w}_H{h}.txt (generated by generate_lms_verify_vector --lms/--lmots).
# W4 uses hardware MMIO acceleration (EXPECTED lookup); SHAKE256 also uses hardware after stage 3 for w!=4 (engine parameterized
# for all w, hw>0 but values differ -> relaxed); SHA-256 engine is still a W4 special case -> w!=4 is pure-software LM-OTS (hw=0, hits do not increase).
W = 4
H = 5

EXPECTED = {
    "sha256": {
        "once": {0: 68, 3: 68, 55: 68, 64: 135, 128: 202},
        "chain": 336,
        "lmots_keygen": 38761,
        "lmots_sign": 23584,
        "lmots_verify": 27327,
        # LMS-layer S6/S8 new accounting (0.1.266): Verify includes D_INTR_CHAIN + MSG_Q_COEF,
        # KeyGen includes full-tree KEYGEN_LEAF, Sign includes randomizer + MSG_Q_COEF.
        "lms_verify": 28341,
        "lms_keygen": 1246681,
        "lms_sign": 23811,
        "lmots_keygen_hits": 1,
        "lmots_sign_hits": 2,
        "lmots_verify_hits": 1,
        "lms_verify_hits": 3,
        "lms_keygen_hits": 63,
        "lms_sign_hits": 3,
    },
    "shake256": {
        "once": {0: 12, 3: 12, 55: 12, 64: 12, 128: 12},
        "chain": 60,
        "lmots_keygen": 8966,   # After P2 (-544 folded)
        "lmots_sign": 5487,     # After P2+P3 (-391 folded -536 background write)
        "lmots_verify": 6468,   # After P2 (-321 folded)
        # Standard flow (same-session keygen->sign->verify) measured = simulated. An isolated session (after flashing,
        # running 0x56 alone) once measured a +48 session artifact (0.1.270 session artifact),
        # a full scan of all 12 parameter sets (0.1.270 rerun) confirmed standard-flow values are stable.
        "lms_verify": 6614,     # After P2: VERIFY_LEAF(6482)+D_INTR_CHAIN(120)+Q(12)
        "lms_keygen": 287732,   # After P2: 32xKEYGEN_LEAF(8980)+31x12
        "lms_sign": 5499,       # After P2+P3: lmots_sign(5487)+Q(12)
        "lmots_keygen_hits": 1,
        "lmots_sign_hits": 2,
        "lmots_verify_hits": 1,
        # SHAKE256 auth-path chained D_INTR primitive (0.1.223): LMS Verify synthesizes 5 D_INTR layers into one
        # D_INTR_CHAIN (hw +65 ticks, Verify hits +7->+3: verify + D_INTR_CHAIN + message hash).
        "lms_verify_hits": 3,
        "lms_keygen_hits": 63,
        "lms_sign_hits": 3,
    },
}


def _hash(data: bytes) -> bytes:
    """32B digest oracle for the hash under test (matches on-board HASH_ONCE/CHAIN semantics)."""
    if HASH_MODE == "shake256":
        return hashlib.shake_256(data).digest(32)
    return hashlib.sha256(data).digest()


def _chain_expected(identifier: bytes, q: int, index: int, start: int, steps: int, value: bytes) -> bytes:
    """CHAIN chained-iteration oracle (I||u32str(q)||u16str(i)||u8str(j)||chain)."""
    expected = value
    for chain_index in range(start, start + steps):
        expected = _hash(
            identifier
            + q.to_bytes(4, "big")
            + index.to_bytes(2, "big")
            + bytes((chain_index,))
            + expected
        )
    return expected

# Secure-domain commands (stage 3, 0x5x range). REQUEST_NVM_SYNC and RESPONSE share 0x52 but have different semantics.
REQUEST_NVM_SYNC = 0x52
NVM_SUB_PUSH_LO = 0x01
NVM_SUB_PUSH_HI = 0x02
NVM_SUB_READ = 0x03
NVM_STATE_LEN = 64
NVM_CHUNK_LEN = 32
NVM_STORE_FILE = Path("build/nvm_state.bin")


def crc16_ccitt(data: bytes) -> int:
    """CRC16-CCITT(0xFFFF), matching the firmware nvm_sync."""
    crc = 0xFFFF
    for byte in data:
        crc ^= byte << 8
        for _ in range(8):
            crc = ((crc << 1) ^ 0x1021) & 0xFFFF if crc & 0x8000 else (crc << 1) & 0xFFFF
    return crc


class NvmStore:
    """Host persistent domain: file mirror of the 64B STATE_REC + push-back/read-back/corruption injection.

    The firmware NVM slot is volatile (cleared on reset); power-off persistence is handled by the host file this class maintains.
    After power-up the runner pushes the file contents back to the firmware via PUSH_LO/HI; firmware NVM_SYNC READ can verify it."""

    def __init__(self, path: Path = NVM_STORE_FILE) -> None:
        self.path = path

    def load(self) -> bytes:
        if not self.path.exists():
            return bytes(NVM_STATE_LEN)
        data = self.path.read_bytes()
        if len(data) != NVM_STATE_LEN:
            raise RuntimeError(f"NvmStore: {self.path} length {len(data)} != {NVM_STATE_LEN}")
        return data

    def save(self, state: bytes) -> None:
        if len(state) != NVM_STATE_LEN:
            raise RuntimeError(f"NvmStore: state length {len(state)} != {NVM_STATE_LEN}")
        self.path.parent.mkdir(parents=True, exist_ok=True)
        self.path.write_bytes(state)

    def clear(self) -> None:
        if self.path.exists():
            self.path.unlink()

    def corrupt(self, offset: int, value: int) -> None:
        """Inject corruption: overwrite one byte of the persistent domain (tests firmware rejection of a corrupt STATE_REC)."""
        data = bytearray(self.load())
        data[offset] = value
        self.save(bytes(data))


def nvm_sync_roundtrip(
    port: serial.Serial, op: int, chunk: bytes | None = None
) -> tuple[int, int, bytes]:
    """Send one NVM_SYNC frame, return (status, valid_mask, data_echo 28B)."""
    request = bytes((REQUEST_NVM_SYNC, op))
    if op in (NVM_SUB_PUSH_LO, NVM_SUB_PUSH_HI):
        if chunk is None or len(chunk) != NVM_CHUNK_LEN:
            raise RuntimeError("nvm_sync: PUSH requires 32B chunk")
        crc = crc16_ccitt(chunk)
        request += chunk + bytes((crc & 0xFF, crc >> 8))
    write_paced(port, request)
    response = read_exact(port, RESPONSE_SIZE)
    if response[0] != RESPONSE or response[1] != 0:
        raise RuntimeError(
            f"nvm_sync: marker=0x{response[0]:02x} status={response[1]}"
        )
    return response[18], response[19], bytes(response[20:48])


def nvm_push_state(port: serial.Serial, state: bytes) -> None:
    """Push the 64B STATE_REC back into the firmware volatile NVM slot in two halves."""
    if len(state) != NVM_STATE_LEN:
        raise RuntimeError(f"nvm_push_state: length {len(state)} != {NVM_STATE_LEN}")
    status, mask, _ = nvm_sync_roundtrip(port, NVM_SUB_PUSH_LO, state[:NVM_CHUNK_LEN])
    if status != 0:
        raise RuntimeError(f"nvm_push_state: PUSH_LO status={status}")
    status, mask, _ = nvm_sync_roundtrip(port, NVM_SUB_PUSH_HI, state[NVM_CHUNK_LEN:])
    if status != 0 or mask != 0x3:
        raise RuntimeError(f"nvm_push_state: PUSH_HI status={status} mask={mask}")


def nvm_read_state_lo28(port: serial.Serial) -> bytes:
    """Read back the first 28B of the firmware NVM lo half (for consistency checks)."""
    status, mask, echo = nvm_sync_roundtrip(port, NVM_SUB_READ)
    if status != 0 or mask != 0x3:
        raise RuntimeError(f"nvm_read: status={status} mask={mask}")
    return echo


def run_nvm_sync_case(port: serial.Serial) -> None:
    """Real board: push STATE_REC back from the persistent-domain file, then read back the first 28B of the lo half to verify consistency."""
    store = NvmStore()
    state = store.load()
    nvm_push_state(port, state)
    echo = nvm_read_state_lo28(port)
    if echo != state[:28]:
        raise RuntimeError(
            f"nvm-sync: read-back mismatch echo={echo.hex()} expected={state[:28].hex()}"
        )
    print(f"PASS: nvm-sync push+read lo28 consistent file={store.path}")


# ---- Stage-3 secure-domain commands (0x55 SEC_STATE / 0x54 SEC_SIGN) ----
REQUEST_SEC_STATE = 0x55
REQUEST_SEC_SIGN = 0x54
# Secured LMS triple (full security-scheme semantics): 0x66 SEC_LMS_SIGN = sec_sign state machine + auth path
# (full LMS signature); 0x67 SEC_LMS_KEYGEN = SEC-slot SEED builds tree and produces root. No plaintext SEED on input.
REQUEST_SEC_LMS_SIGN = 0x66
REQUEST_SEC_LMS_KEYGEN = 0x67
REQUEST_SEC_LMS_KEYGEN_NEW = 0x68
SEC_SUB_COMMIT = 0x01
SEC_SUB_READ_ACTIVE = 0x02
SEC_SUB_INJECT_TAG = 0x04
SEC_SUB_BOOT = 0x05
SEC_SUB_FACTORY_INIT = 0x06
SEC_SUB_GET_STATE = 0x07
SEC_SUB_NVM_LOAD = 0x08
SEC_SUB_MC_LOAD = 0x0A
SEC_SUB_WRAP_LOAD = 0x0B
SEC_SUB_WRAPPED_READ_LO = 0x0C
SEC_SUB_WRAPPED_READ_HI = 0x0D
LMOTS_SIG_LEN = 4 + 32 + 67 * 32  # 2180


def sec_cmd(port: serial.Serial, sub: int, params: bytes = b"") -> bytes:
    """Send a SEC_STATE subcommand, return the 48B response."""
    write_paced(port, bytes((REQUEST_SEC_STATE, sub)) + params)
    response = read_exact(port, RESPONSE_SIZE)
    if response[0] != RESPONSE or response[16] != sub:
        raise RuntimeError(f"sec_cmd: marker=0x{response[0]:02x} sub=0x{response[16]:02x}")
    return response


def sec_get_state(port: serial.Serial) -> tuple[int, int, int]:
    """Return (state, ctr, last_tx). Single-key fixed scheme has no key_handle."""
    r = sec_cmd(port, SEC_SUB_GET_STATE)
    state = struct.unpack_from(">I", r, 20)[0]
    ctr = struct.unpack_from(">I", r, 24)[0]
    last_tx = struct.unpack_from(">I", r, 28)[0]
    return state, ctr, last_tx


def sec_get_state_full(port: serial.Serial) -> tuple[int, int, int, int]:
    """Return (state, ctr, last_tx, active_slot)."""
    r = sec_cmd(port, SEC_SUB_GET_STATE)
    state = struct.unpack_from(">I", r, 20)[0]
    ctr = struct.unpack_from(">I", r, 24)[0]
    last_tx = struct.unpack_from(">I", r, 28)[0]
    active_slot = r[39]
    return state, ctr, last_tx, active_slot


def sec_boot(port: serial.Serial, key_i: bytes) -> tuple[int, int]:
    """CMD_BOOT, return (state, ctr). key_i = active-key public-key ID (16B, KDF context, not secret)."""
    if len(key_i) != 16:
        raise RuntimeError("sec_boot: key_i needs 16B")
    r = sec_cmd(port, SEC_SUB_BOOT, key_i)
    return struct.unpack_from(">I", r, 20)[0], struct.unpack_from(">I", r, 24)[0]


def _key_i(vec: dict[str, str]) -> bytes:
    """Extract public-key identifier I from the test-vector private key (LMS private key offset 8..24, 16B)."""
    return bytes.fromhex(vec["PRIVATE_KEY"])[8:24]


def sec_commit(port: serial.Serial, new_state: int, ctr: int, reserved_q: int) -> tuple[int, int]:
    """CMD COMMIT, return (status, tx)."""
    params = struct.pack(">III", new_state, ctr, reserved_q)
    r = sec_cmd(port, SEC_SUB_COMMIT, params)
    return r[18], struct.unpack_from(">I", r, 20)[0]


def sec_mc_load(port: serial.Serial, value: int) -> None:
    r = sec_cmd(port, SEC_SUB_MC_LOAD, struct.pack(">I", value))
    if r[18] != 0:
        raise RuntimeError(f"sec_mc_load: status={r[18]}")


def sec_nvm_load(port: serial.Serial, slot: int, rec: bytes) -> None:
    if len(rec) != 64:
        raise RuntimeError("sec_nvm_load: rec needs 64B")
    r = sec_cmd(port, SEC_SUB_NVM_LOAD, bytes((slot,)) + rec)
    if r[18] != 0:
        raise RuntimeError(f"sec_nvm_load: status={r[18]}")


def sec_wrapped_read(port: serial.Serial) -> bytes:
    """Fetch the 48B wrapped blob: LO=28B (blob[0..27]) + HI=20B (blob[28..47]),
    response body is capped at 28B (same accounting as NVM_READ)."""
    blob = bytearray(48)
    r = sec_cmd(port, SEC_SUB_WRAPPED_READ_LO)
    if r[18] != 0:
        raise RuntimeError(f"wrapped_read_lo: status={r[18]}")
    for i in range(28):
        blob[i] = r[20 + i]
    r = sec_cmd(port, SEC_SUB_WRAPPED_READ_HI)
    if r[18] != 0:
        raise RuntimeError(f"wrapped_read_hi: status={r[18]}")
    for i in range(20):
        blob[28 + i] = r[20 + i]
    return bytes(blob)


def sec_wrap_load(port: serial.Serial, blob: bytes) -> None:
    if len(blob) != 48:
        raise RuntimeError("sec_wrap_load: blob needs 48B")
    r = sec_cmd(port, SEC_SUB_WRAP_LOAD, blob)
    if r[18] != 0:
        raise RuntimeError(f"sec_wrap_load: status={r[18]}")


def nvm_read_full64(port: serial.Serial) -> bytes:
    """Three parameterless READs fetch the full 64B of the active slot (including tag)."""
    rec = bytearray(64)
    for op, base in ((0x03, 0), (0x05, 28), (0x04, 36)):
        write_paced(port, bytes((REQUEST_NVM_SYNC, op)))
        r = read_exact(port, RESPONSE_SIZE)
        if r[18] != 0 or r[19] != 3:
            raise RuntimeError(f"nvm_read64: op={op} status={r[18]} mask={r[19]}")
        for i in range(28):
            if base + i < 64:
                rec[base + i] = r[20 + i]
    return bytes(rec)


def sec_sign(port: serial.Serial, vector: dict[str, str]) -> tuple[int, int, bytes, int, int, int]:
    """SEC_SIGN atomic signature, return (status, q_out, signature, sign_rc, hw_cycles, total_cycles).
    sign_rc = specific lmots_sign error code (diagnostic, firmware nvm_response[3] -> response frame[19]).
    hw_cycles = frame[4..7] (hardware derive+sign compressed ticks); total_cycles = frame[20..23]
    (end-to-end SOC_CYCLE_COUNT delta, same offset as normal commands).
    Types are read from the vector private key per parameter set (lms_private_key: lms_type(4)||lmots_type(4)||I(16)||
    seed(32)||q(4), big-endian), signature length derived from vector LMOTS_SIGNATURE (all w supported).
    Single-key fixed scheme: no key_handle field (SEC-slot SEED loaded by provisioning)."""
    priv = bytes.fromhex(vector["PRIVATE_KEY"])
    message = bytes.fromhex(vector["MESSAGE"])
    i_field = priv[8:24]
    lms_type = int.from_bytes(priv[0:4], "big")
    lmots_type = int.from_bytes(priv[4:8], "big")
    request = bytearray((REQUEST_SEC_SIGN,))
    request += i_field
    request += struct.pack("<I", lms_type)
    request += struct.pack("<I", lmots_type)
    request += struct.pack(">H", len(message)) + message
    write_paced(port, bytes(request))
    response = read_exact(port, RESPONSE_SIZE)
    if response[0] != RESPONSE:
        raise RuntimeError(f"sec_sign: marker=0x{response[0]:02x}")
    status = response[18]
    # sign_rc (specific lmots_sign code) is placed by firmware in nvm_response[3] -> serve_uart sends it in response frame [19]
    sign_rc = response[19]
    q_out = struct.unpack_from(">I", response, 36)[0]
    hw_cycles = struct.unpack_from("<I", response, 4)[0]
    total_cycles = struct.unpack_from("<I", response, 20)[0]
    signature = b""
    if response[1] == 0 and status == 0:
        signature = read_exact(port, len(bytes.fromhex(vector["LMOTS_SIGNATURE"])))
    return status, q_out, signature, sign_rc, hw_cycles, total_cycles


def gen_sec_expected_sig(q: int, vector: dict[str, str]) -> bytes:
    """Use the PC generator to produce the expected LM-OTS signature for q (SEC_SIGN signature = lmots_sign(q, vector message),
    consistent with the Verilator secsign-1 comparison logic). The generator uses fixed I/seed, same source as the vector."""
    priv = bytes.fromhex(vector["PRIVATE_KEY"])
    lms_type = int.from_bytes(priv[0:4], "big")
    lmots_type = int.from_bytes(priv[4:8], "big")
    out = subprocess.run(
        ["build/generate_lms_verify_vector.exe", f"--lms={lms_type}",
         f"--lmots={lmots_type}", f"--q={q}"],
        capture_output=True, text=True, cwd=str(Path(__file__).resolve().parents[2]),
    ).stdout
    m = re.search(r"LMOTS_SIGNATURE=([0-9a-fA-F]+)", out)
    if not m:
        raise RuntimeError(f"gen_sec_expected_sig: generator failed for q={q}")
    return bytes.fromhex(m.group(1))


def gen_lms_expected_sig(q: int, vector: dict[str, str]) -> bytes:
    """Use the PC generator to produce the full expected LMS signature for q (0x66 SEC_LMS_SIGN = lms_sign(q, vector
    message) including auth path). SEC-slot SEED = vector seed (provision consistent) -> expectation matches."""
    priv = bytes.fromhex(vector["PRIVATE_KEY"])
    lms_type = int.from_bytes(priv[0:4], "big")
    lmots_type = int.from_bytes(priv[4:8], "big")
    out = subprocess.run(
        ["build/generate_lms_verify_vector.exe", f"--lms={lms_type}",
         f"--lmots={lmots_type}", f"--q={q}"],
        capture_output=True, text=True, cwd=str(Path(__file__).resolve().parents[2]),
    ).stdout
    m = re.search(r"SIGNATURE=([0-9a-fA-F]+)", out)
    if not m:
        raise RuntimeError(f"gen_lms_expected_sig: generator failed for q={q}")
    return bytes.fromhex(m.group(1))


def sec_lms_sign(port: serial.Serial, vector: dict[str, str],
                 timeout: float = 60.0,
                 i_override: bytes = b"") -> tuple[int, int, bytes, int, int, int]:
    """SEC_LMS_SIGN (0x66): secured full LMS signature (sec_sign state machine + auth path).
    Return (status, q, signature, hw_cycles, total_cycles, steady_total).
    Request: I(16)||lms_type(4)||lmots_type(4)||msg_len(2,BE)||message (single-key fixed scheme
    has no key_handle).
    i_override: when non-empty use these 16B as I (device I=pub[8:24] from the device KeyGen-produced public key, for deploy
    self-consistency); when empty use the vector I (priv[8:24]).
    Response: frame[4..7]=hw; [16..19]=q; [20..23]=total; [24..27]=steady. Signature follows."""
    priv = bytes.fromhex(vector["PRIVATE_KEY"])
    message = bytes.fromhex(vector["MESSAGE"])
    i_field = i_override if len(i_override) == 16 else priv[8:24]
    lms_type = int.from_bytes(priv[0:4], "big")
    lmots_type = int.from_bytes(priv[4:8], "big")
    request = bytearray((REQUEST_SEC_LMS_SIGN,))
    request += i_field
    request += struct.pack("<I", lms_type)
    request += struct.pack("<I", lmots_type)
    request += struct.pack(">H", len(message)) + message
    original_timeout = port.timeout
    try:
        port.timeout = timeout
        write_paced(port, bytes(request))
        response = read_exact(port, RESPONSE_SIZE)
    finally:
        port.timeout = original_timeout
    if response[0] != RESPONSE:
        raise RuntimeError(f"sec_lms_sign: marker=0x{response[0]:02x}")
    status = response[1]
    q = struct.unpack_from("<I", response, 16)[0]
    hw = struct.unpack_from("<I", response, 4)[0]
    total = struct.unpack_from("<I", response, 20)[0]
    steady = struct.unpack_from("<I", response, 24)[0]
    signature = b""
    if status == 0:
        signature = read_exact(port, len(bytes.fromhex(vector["SIGNATURE"])))
    return status, q, signature, hw, total, steady


def sec_lms_keygen(port: serial.Serial, vector: dict[str, str],
                   timeout: float = 120.0) -> tuple[int, bytes, int, int]:
    """SEC_LMS_KEYGEN (0x67): secured LMS KeyGen (SEC-slot SEED builds tree and produces root).
    Return (status, public_key, hw_cycles, total_cycles). Public key follows.
    Request: lms_type(4)||lmots_type(4) (I taken by device from sec_key_I = vector I; single-key fixed scheme has no key_handle)."""
    priv = bytes.fromhex(vector["PRIVATE_KEY"])
    lms_type = int.from_bytes(priv[0:4], "big")
    lmots_type = int.from_bytes(priv[4:8], "big")
    request = bytearray((REQUEST_SEC_LMS_KEYGEN,))
    request += struct.pack("<I", lms_type)
    request += struct.pack("<I", lmots_type)
    original_timeout = port.timeout
    try:
        port.timeout = timeout
        write_paced(port, bytes(request))
        response = read_exact(port, RESPONSE_SIZE)
    finally:
        port.timeout = original_timeout
    if response[0] != RESPONSE:
        raise RuntimeError(f"sec_lms_keygen: marker=0x{response[0]:02x}")
    status = response[1]
    hw = struct.unpack_from("<I", response, 4)[0]
    total = struct.unpack_from("<I", response, 20)[0]
    public_key = b""
    if status == 0:
        public_key = read_exact(port, len(bytes.fromhex(vector["PUBLIC_KEY"])))
    return status, public_key, hw, total


def sec_lms_keygen_new(port: serial.Serial, vector: dict[str, str],
                       i_new: bytes, timeout: float = 120.0) -> tuple[int, bytes, int, int]:
    """SEC_LMS_KEYGEN_NEW (0x68): multi-key rotation - generate and activate a **new key**.
    Return (status, public_key, hw_cycles, total_cycles). Public key follows.
    Request: I(16)||lms_type(4)||lmots_type(4). I/SEED sources are isolated at compile time:
    test semantics = host provides I (different per key) + 0x63 preloaded SEED; deploy semantics (0.1.281 model B) =
    i_new ignored, new SEED+I generated on the fly by the on-device TRNG (controlled load via CMD_SEED_WRITE_SAFE)."""
    if len(i_new) != 16:
        raise RuntimeError("sec_lms_keygen_new: i_new needs 16B")
    priv = bytes.fromhex(vector["PRIVATE_KEY"])
    lms_type = int.from_bytes(priv[0:4], "big")
    lmots_type = int.from_bytes(priv[4:8], "big")
    request = bytearray((REQUEST_SEC_LMS_KEYGEN_NEW,))
    request += i_new
    request += struct.pack("<I", lms_type)
    request += struct.pack("<I", lmots_type)
    original_timeout = port.timeout
    try:
        port.timeout = timeout
        write_paced(port, bytes(request))
        response = read_exact(port, RESPONSE_SIZE)
    finally:
        port.timeout = original_timeout
    if response[0] != RESPONSE:
        raise RuntimeError(f"sec_lms_keygen_new: marker=0x{response[0]:02x}")
    status = response[1]
    hw = struct.unpack_from("<I", response, 4)[0]
    total = struct.unpack_from("<I", response, 20)[0]
    public_key = b""
    if status == 0:
        public_key = read_exact(port, len(bytes.fromhex(vector["PUBLIC_KEY"])))
    return status, public_key, hw, total


def board_reset(port: serial.Serial) -> None:
    """Controlled reset: pull sys_rst_n low via DTR (if wired), otherwise rely on a power-cycle hint.
    On the DaVinci Pro sys_rst_n is usually wired to a button; the UART cannot reset directly.
    GPIO is unavailable here, so degrade to: notify the user to reset manually or let the caller skip."""
    # A real board cannot reset the FPGA over UART; power-loss simulation relies on the runner reopening the serial port + the on-board reset button.
    # This function is kept as a hook; fault-injection cases on the board rely mainly on "half-write/rollback injection" (no power loss).
    raise NotImplementedError("board power-loss test requires manual reset; use injection cases instead")


def run_sec_board_cases(port: serial.Serial, vector: dict[str, str]) -> None:
    """On-board secure-domain closed loop (spec §13 board-testable items): FACTORY_INIT/BOOT/SEC_SIGN q increment/
    exhaustion + half-write/rollback injection. Power-loss cases (3/4) already verified in Verilator,
    board tests focus on injection cases. (Single-key fixed scheme has no key_handle, bad_handle not applicable, REVIEW B13B16-R3.)"""
    # FACTORY_INIT + BOOT (fresh). factory_locked may already be set if the FPGA was not reset:
    # first run initializes with status=0, repeated runs get status=8 (already locked) and skip INIT straight to BOOT.
    r = sec_cmd(port, SEC_SUB_FACTORY_INIT, _key_i(vector))
    if r[18] == 0:
        if r[20] != 0x46:
            raise RuntimeError(f"factory_init: magic=0x{r[20]:02x}")
        print(f"PASS: board factory-init dev_epoch={struct.unpack_from('>I', r, 24)[0]:08x}")
        # Repeated INIT rejected (ERR_FACTORY_LOCKED=8)
        r2 = sec_cmd(port, SEC_SUB_FACTORY_INIT, _key_i(vector))
        if r2[18] != 8:
            raise RuntimeError(f"factory_relock: status={r2[18]} (expect 8)")
        print("PASS: board factory-relock rejected status=8")
    elif r[18] == 8:
        print("PASS: board factory-init already locked (status=8, reuse)")
    else:
        raise RuntimeError(f"factory_init: status={r[18]} magic=0x{r[20]:02x}")
    # BOOT fresh
    state, ctr = sec_boot(port, _key_i(vector))
    if state != 1:
        raise RuntimeError(f"boot fresh: state={state} (expect 1 IDLE)")
    print(f"PASS: board boot-fresh state=IDLE ctr={ctr}")

    # SEC-slot SEED provisioning (aligned with SoC secsign: 0x63 SEED_LOAD_TEST + 32B vector seed).
    # After FACTORY_INIT the SEC-slot SEED must be reloaded, otherwise sec_sign hardware signing has no SEED -> SEC_ERR_PATH(5).
    priv = bytes.fromhex(vector["PRIVATE_KEY"])
    write_paced(port, bytes((0x63,)) + priv[24:56])
    seed_resp = read_exact(port, RESPONSE_SIZE)
    if seed_resp[1] != 0:
        raise RuntimeError(f"seed-load-test: status={seed_resp[1]}")
    print("PASS: board seed-load-test (SEC slot seed provisioned)")

    # Spec §13 test 1: SEC_SIGN q strictly increasing + signature correctness.
    # SEC-domain q continues from the persisted ctr (FACTORY_INIT locks once, ctr cannot be reset back to 0),
    # expected signature = PC generator lmots_sign(q=ctr, vector message) (aligned with Verilator secsign-1 q=0).
    expected_sig = gen_sec_expected_sig(ctr, vector)
    status, q0, sig0, sign_rc, hw_sec, tot_sec = sec_sign(port, vector)
    if status != 0 or q0 != ctr or sig0 != expected_sig:
        raise RuntimeError(f"sec_sign-1: status={status} q={q0} sig_match={sig0 == expected_sig} sign_rc={sign_rc}")
    state1, ctr1, _ = sec_get_state(port)
    if state1 != 1 or ctr1 != ctr + 1:
        raise RuntimeError(f"sec_sign-1 post: state={state1} ctr={ctr1} (expect ctr={ctr+1})")
    print(f"PASS: board sec_sign-1 q={q0} committed ctr={ctr1} (Release=>Committed)")
    # Secure-domain signing performance (frame[4..7]=hw, frame[20..23]=total end-to-end). Compared with insecure signing
    # (W4_H5 board reference: total 28147 / steady 25911 / hw 6414), quantifies SEC's own performance cost.
    print(f"  sec_sign perf: hw_cycles={hw_sec} total_cycles={tot_sec} sw_overhead={tot_sec - hw_sec}")
    status, q1, _, _, _, _ = sec_sign(port, vector)
    if status != 0 or q1 != ctr1:
        raise RuntimeError(f"sec_sign-2: status={status} q={q1} (expect q={ctr1})")
    print(f"PASS: board sec_sign-2 q={q1} strictly increasing")

    # 0.1.269 H1 hardening: UART COMMIT rollback rejected (ctr monotonic + legal-transition whitelist).
    # Attack prototype: COMMIT(IDLE, ctr=0) could once reset sec_ctr -> re-signing released q=0.
    _, ctr_before_back, _ = sec_get_state(port)
    st_back, _ = sec_commit(port, 1, 0, 0)
    if st_back == 0:
        raise RuntimeError(f"h1-rollback-commit: status={st_back} (expect reject)")
    _, ctr_after_back, _ = sec_get_state(port)
    if ctr_after_back != ctr_before_back:
        raise RuntimeError(f"h1-rollback-commit: ctr={ctr_after_back} (expect unchanged {ctr_before_back})")
    print(f"PASS: board h1-rollback-commit rejected status={st_back} ctr={ctr_after_back} unchanged")

    # Spec §13 test 5: half-write (high-tx slot tag corrupted) -> BOOT picks the low-tx valid slot
    # tag is bound to slot_id (AAD contains slot_id), injection must keep the original slot.
    _, _, _, slot_new = sec_get_state_full(port)
    rec_new = bytearray(nvm_read_full64(port))           # current active (ctr=cur_ctr, low tx)
    cur_state, cur_ctr, cur_tx = sec_get_state(port)
    st, _ = sec_commit(port, 1, cur_ctr + 1, 0)          # new valid record ctr+1 (higher tx, other slot)
    if st != 0:
        raise RuntimeError(f"halfwrite commit: status={st}")
    _, _, _, slot_high = sec_get_state_full(port)
    rec_high = bytearray(nvm_read_full64(port))          # ctr+1 record (high tx)
    _, _, tx_high = sec_get_state(port)
    rec_high[48] ^= 0xFF  # corrupt the tag (half-write did not finish writing the tag)
    # Inject back into original slots: bad high slot + good low slot, BOOT should skip the bad high slot and pick the good low slot.
    sec_nvm_load(port, slot_high, bytes(rec_high))
    sec_nvm_load(port, slot_new, bytes(rec_new))
    sec_mc_load(port, tx_high)
    r_boot = sec_cmd(port, SEC_SUB_BOOT, _key_i(vector))
    state_b, ctr_b = struct.unpack_from(">I", r_boot, 20)[0], struct.unpack_from(">I", r_boot, 24)[0]
    if state_b != 1 or ctr_b != cur_ctr:
        print(f"DIAG: halfwrite boot valid={r_boot[40]}/{r_boot[41]} diag={r_boot[42]}/{r_boot[43]} cur_ctr={cur_ctr} tx_high={tx_high}")
        raise RuntimeError(f"halfwrite boot: state={state_b} ctr={ctr_b} (expect ctr={cur_ctr})")
    print(f"PASS: board half-write rejected state=IDLE ctr={ctr_b} (corrupt high-tx slot skipped)")

    # Spec §13 test 4: rollback (replay old tx slot) -> BOOT picks the new tx slot
    # after half-write active=rec_new (ctr=cur_ctr). commit ctr+1 (higher tx, other slot).
    _, _, _, slot_old2 = sec_get_state_full(port)
    rec_old2 = bytearray(nvm_read_full64(port))          # current active (ctr=cur_ctr, low tx)
    st, _ = sec_commit(port, 1, cur_ctr + 1, 0)
    if st != 0:
        raise RuntimeError(f"rollback commit: status={st}")
    _, _, _, slot_newer = sec_get_state_full(port)
    rec_newer = bytearray(nvm_read_full64(port))         # ctr+1 (high tx)
    _, _, tx_new2 = sec_get_state(port)
    # Inject back into original slots: new slot + old slot (replaying old state) -> BOOT picks the high tx.
    sec_nvm_load(port, slot_old2, bytes(rec_old2))
    sec_nvm_load(port, slot_newer, bytes(rec_newer))
    sec_mc_load(port, tx_new2)
    r_rb = sec_cmd(port, SEC_SUB_BOOT, _key_i(vector))
    state_r, ctr_r = struct.unpack_from(">I", r_rb, 20)[0], struct.unpack_from(">I", r_rb, 24)[0]
    if state_r != 1 or ctr_r != cur_ctr + 1:
        print(f"DIAG: rollback boot valid={r_rb[40]}/{r_rb[41]} diag={r_rb[42]}/{r_rb[43]} tx_new2={tx_new2} cur_ctr={cur_ctr}")
        raise RuntimeError(f"rollback boot: state={state_r} ctr={ctr_r} (expect ctr={cur_ctr+1})")
    print(f"PASS: board rollback rejected state=IDLE ctr={ctr_r} (chose newer tx)")

    # Spec §13 test 7: verify/public commands are stateless - STATE_REC unchanged around non-secure-domain commands.
    # Placed before exhaust (exhaust advances the firmware to ST_EXHAUSTED, polluting later steps).
    # On-board verify long frames (2533B) occasionally drop UART bytes (historical uart_rx reliability), so board tests use
    # short-frame public commands (HASH_ONCE/CHAIN, also through the accelerator and also must not touch STATE_REC) to verify
    # the "public commands are stateless" semantics; the full CMD_VERIFY_CHAIN stateless assertion is covered in Verilator.
    state_v0, ctr_v0, tx_v0 = sec_get_state(port)
    # HASH_ONCE expected cycles per platform (SHA-256=68, SHAKE256=12, EXPECTED once[3]=abc)
    once_cyc = EXPECTED[HASH_MODE]["once"][3]
    hits_h = run_case(port, "sec-stateless-hash", b"abc", once_cyc, None)
    _ = run_chain_case(port, hits_h)
    state_v1, ctr_v1, tx_v1 = sec_get_state(port)
    if (state_v0, ctr_v0, tx_v0) != (state_v1, ctr_v1, tx_v1):
        raise RuntimeError(f"stateless: before=({state_v0},{ctr_v0},{tx_v0}) after=({state_v1},{ctr_v1},{tx_v1})")
    print(f"PASS: board stateless-public-cmd ctr={ctr_v1} tx={tx_v1} unchanged")

    # Spec §13 test 8: exhaustion - signing rejected after commit ctr=32 (done last, advances EXHAUSTED)
    st, _ = sec_commit(port, 1, 32, 0)
    if st != 0:
        raise RuntimeError(f"exhaust commit: status={st}")
    status, _, _, _, _, _ = sec_sign(port, vector)
    if status != 6:
        raise RuntimeError(f"sec_sign-exhausted: status={status} (expect 6)")
    print("PASS: board sec_sign-exhausted rejected status=6 (ctr=32)")

    # Cleanup: exhaust commits EXHAUSTED into the persistent slot, BOOT would restore EXHAUSTED (spec §6 correct
    # semantics, but it prevents the next closed loop from starting fresh). Inject two all-zero slots + BOOT, reset the secure domain to
    # factory state, so --sec-board-test is repeatable (test convenience only, not real device behavior).
    # Note: must not mc_load(0) - an mc rollback would make the next commit's tx<=sec_last_tx be rejected as rollback.
    zero = bytes(64)
    sec_nvm_load(port, 0, zero)
    sec_nvm_load(port, 1, zero)
    sec_cmd(port, SEC_SUB_BOOT, _key_i(vector))
    print("PASS: board cleanup zero-slots (repeatable)")

    print("PASS: board secure-domain closed loop (factory/boot/sec_sign/half-write/rollback/verify-stateless/exhaust)")


def run_sec_lms_cases(port: serial.Serial, vector: dict[str, str]) -> None:
    """Secured LMS triple (full security-scheme semantics): FACTORY_INIT/BOOT/seed provision ->
    0x67 SEC KeyGen (SEC-slot SEED builds tree and produces root) -> 0x66 SEC Sign (sec_sign state machine + auth path)
    -> 0x56 Verify. Verifies public-key/signature correctness + q increment + Release=>Committed, quantifies the security cost."""
    # FACTORY_INIT + BOOT (fresh)
    r = sec_cmd(port, SEC_SUB_FACTORY_INIT, _key_i(vector))
    if r[18] == 0:
        if r[20] != 0x46:
            raise RuntimeError(f"factory_init: magic=0x{r[20]:02x}")
        r2 = sec_cmd(port, SEC_SUB_FACTORY_INIT, _key_i(vector))
        if r2[18] != 8:
            raise RuntimeError(f"factory_relock: status={r2[18]} (expect 8)")
    elif r[18] != 8:
        raise RuntimeError(f"factory_init: status={r[18]}")
    state, ctr = sec_boot(port, _key_i(vector))
    if state != 1:
        raise RuntimeError(f"boot fresh: state={state} (expect 1 IDLE)")
    print(f"PASS: board boot-fresh state=IDLE ctr={ctr}")

    # SEC-slot SEED provisioning (= vector seed, guarantees public key/signature match PC expectations)
    priv = bytes.fromhex(vector["PRIVATE_KEY"])
    write_paced(port, bytes((0x63,)) + priv[24:56])
    seed_resp = read_exact(port, RESPONSE_SIZE)
    if seed_resp[1] != 0:
        raise RuntimeError(f"seed-load-test: status={seed_resp[1]}")
    print("PASS: board seed-load-test (SEC slot seed provisioned)")

    # 0x67 SEC KeyGen: public key = vector PUBLIC_KEY (SEC-slot SEED builds tree and produces root, KeyGen semantics
    # do not consume signing state; performance compared with insecure LMS KeyGen).
    status, pub, hw_kg, tot_kg = sec_lms_keygen(port, vector)
    expected_pub = bytes.fromhex(vector["PUBLIC_KEY"])
    if status != 0 or pub != expected_pub:
        raise RuntimeError(f"sec-lms-keygen: status={status} pub_match={pub == expected_pub}")
    print(f"PASS: board sec-lms-keygen pub_match ✓ hw={hw_kg} total={tot_kg}")

    # 0x66 SEC Sign (q=ctr): signature = full LMS signature (sec_sign sigma_q + auth path)
    expected_sig = gen_lms_expected_sig(ctr, vector)
    status, q0, sig0, hw_s, tot_s, steady_s = sec_lms_sign(port, vector)
    if status != 0 or q0 != ctr or sig0 != expected_sig:
        raise RuntimeError(
            f"sec-lms-sign-1: status={status} q={q0}/{ctr} sig_match={sig0 == expected_sig}")
    state1, ctr1, _ = sec_get_state(port)
    if state1 != 1 or ctr1 != ctr + 1:
        raise RuntimeError(f"sec-lms-sign-1 post: state={state1} ctr={ctr1} (expect ctr={ctr+1})")
    print(f"PASS: board sec-lms-sign-1 q={q0} committed ctr={ctr1} (Release=>Committed)")
    print(f"  sec-lms-sign perf: hw={hw_s} total={tot_s} steady={steady_s}")

    # 0x66 second time (q=ctr+1): q strictly increasing + state advance
    status, q1, _, _, _, _ = sec_lms_sign(port, vector)
    if status != 0 or q1 != ctr1:
        raise RuntimeError(f"sec-lms-sign-2: status={status} q={q1} (expect q={ctr1})")
    print(f"PASS: board sec-lms-sign-2 q={q1} strictly increasing")

    # 0x56 Verify: public key verifies the secured signature (no-key/no-state semantics)
    msg = bytes.fromhex(vector["MESSAGE"])
    verify_request = (
        bytes((REQUEST_VERIFY,)) + expected_pub
        + struct.pack(">H", len(msg)) + msg + sig0
    )
    original_timeout = port.timeout
    try:
        port.timeout = 60.0
        write_paced(port, verify_request, chunk_size=4, sleep_time=0.004)
        rv = read_exact(port, RESPONSE_SIZE)
    finally:
        port.timeout = original_timeout
    if rv[1] != 0:
        raise RuntimeError(f"sec-lms-verify: status={rv[1]} hex={rv[:8].hex()}")
    print("PASS: board sec-lms-verify (public key verifies secured signature)")

    # Cleanup: reset the secure domain to factory state (repeatable)
    zero = bytes(64)
    sec_nvm_load(port, 0, zero)
    sec_nvm_load(port, 1, zero)
    sec_cmd(port, SEC_SUB_BOOT, _key_i(vector))
    print("PASS: board cleanup zero-slots (repeatable)")
    print("PASS: board secured LMS triple (0x67 KeyGen / 0x66 Sign / Verify)")


def run_sec_lms_keygen_new_cases(port: serial.Serial, vector: dict[str, str]) -> None:
    """Multi-key rotation (0x68 KEYGEN_NEW, test semantics): FACTORY_INIT/BOOT/seed provision ->
    0x67 KeyGen (pubA=vector) -> 0x66 Sign q=0 (ctr=1) -> swap to new SEED+new I -> 0x68 KeyGen_NEW
    (pubB!=pubA, new I takes effect) -> reset ctr=0/state=IDLE -> 0x66 Sign q=0 (using pubB's I) ->
    Verify self-consistent closed loop. Verifies cross-key isolation + q reset to zero after key rotation (STATE_REC cleared)."""
    # FACTORY_INIT + BOOT (fresh; factory relock tolerated on rerun)
    r = sec_cmd(port, SEC_SUB_FACTORY_INIT, _key_i(vector))
    if r[18] == 0:
        if r[20] != 0x46:
            raise RuntimeError(f"keygennew_factory_init: magic=0x{r[20]:02x}")
        r2 = sec_cmd(port, SEC_SUB_FACTORY_INIT, _key_i(vector))
        if r2[18] != 8:
            raise RuntimeError(f"keygennew_factory_relock: status={r2[18]} (expect 8)")
    elif r[18] != 8:
        raise RuntimeError(f"keygennew_factory_init: status={r[18]}")
    state, ctr = sec_boot(port, _key_i(vector))
    if state != 1:
        raise RuntimeError(f"keygennew_boot fresh: state={state} (expect 1 IDLE)")
    print(f"PASS: board keygennew boot-fresh state=IDLE ctr={ctr}")

    # SEC-slot SEED provisioning (= vector seed -> 0x67 builds tree to get vector public key)
    priv = bytes.fromhex(vector["PRIVATE_KEY"])
    write_paced(port, bytes((0x63,)) + priv[24:56])
    if read_exact(port, RESPONSE_SIZE)[1] != 0:
        raise RuntimeError("keygennew seed-load-test: status!=0")
    print("PASS: board keygennew seed-load-test")

    # 0x67 KeyGen (baseline): public key = vector PUBLIC_KEY
    status, pub_a, hw_kg, tot_kg = sec_lms_keygen(port, vector)
    expected_pub = bytes.fromhex(vector["PUBLIC_KEY"])
    if status != 0 or pub_a != expected_pub:
        raise RuntimeError(f"keygennew-0x67: status={status} pub_match={pub_a == expected_pub}")
    print(f"PASS: board keygennew-0x67 pubA == vector pub (baseline) hw={hw_kg} total={tot_kg}")

    # 0x66 Sign q=ctr (first consume one key's q)
    expected_sig = gen_lms_expected_sig(ctr, vector)
    status, q0, sig0, _, _, _ = sec_lms_sign(port, vector)
    if status != 0 or q0 != ctr or sig0 != expected_sig:
        raise RuntimeError(f"keygennew-sign-a: status={status} q={q0}/{ctr} sig_match={sig0 == expected_sig}")
    state1, ctr1, _ = sec_get_state(port)
    if state1 != 1 or ctr1 != ctr + 1:
        raise RuntimeError(f"keygennew-sign-a post: state={state1} ctr={ctr1} (expect ctr={ctr+1})")
    print(f"PASS: board keygennew pre-rotate ctr={ctr1} (q consumed)")

    # Swap to new SEED (external input, different from vector seed) + new I (different per key)
    seed_new = bytes([b ^ 0xff for b in priv[24:56]])
    i_new = bytes([b ^ 0xff for b in _key_i(vector)])
    write_paced(port, bytes((0x63,)) + seed_new)
    if read_exact(port, RESPONSE_SIZE)[1] != 0:
        raise RuntimeError("keygennew seed2-load-test: status!=0")
    print("PASS: board keygennew seed2 loaded (new SEED)")

    # 0x68 KeyGen_NEW: new I + new SEED build tree -> pubB != pubA; reset ctr=0/state=IDLE
    status, pub_b, hw_kn, tot_kn = sec_lms_keygen_new(port, vector, i_new)
    if status != 0 or len(pub_b) != len(expected_pub):
        raise RuntimeError(f"keygennew-0x68: status={status} pub_len={len(pub_b)}")
    if pub_b == pub_a:
        raise RuntimeError("keygennew-0x68: pubB == pubA (expected different key)")
    print(f"PASS: board keygennew-0x68 pubB != pubA (cross-key isolation) hw={hw_kn} total={tot_kn}")

    state2, ctr2, _ = sec_get_state(port)
    if state2 != 1 or ctr2 != 0:
        raise RuntimeError(f"keygennew-0x68 post: state={state2} ctr={ctr2} (expect IDLE/0)")
    print(f"PASS: board keygennew post-rotate state=IDLE ctr=0 (fresh q)")

    # 0x66 Sign q=0 uses pubB's I (I generated by device KeyGen) -> self-consistent with pubB.
    # sec_lms_sign always uses the vector I; here I must be device_i_b (pubB[8:24]), so the request is constructed inline.
    device_i_b = pub_b[8:24]
    msg = bytes.fromhex(vector["MESSAGE"])
    lms_type = int.from_bytes(priv[0:4], "big")
    lmots_type = int.from_bytes(priv[4:8], "big")
    sign_request = bytearray((REQUEST_SEC_LMS_SIGN,))
    sign_request += device_i_b
    sign_request += struct.pack("<I", lms_type)
    sign_request += struct.pack("<I", lmots_type)
    sign_request += struct.pack(">H", len(msg)) + msg
    original_timeout = port.timeout
    try:
        port.timeout = 60.0
        write_paced(port, bytes(sign_request))
        sr = read_exact(port, RESPONSE_SIZE)
    finally:
        port.timeout = original_timeout
    qb = struct.unpack_from("<I", sr, 16)[0]
    sigb = read_exact(port, len(bytes.fromhex(vector["SIGNATURE"])))
    if sr[0] != RESPONSE or sr[1] != 0 or qb != 0:
        raise RuntimeError(f"keygennew-sign-b: status={sr[1]} q={qb} (expect q=0)")
    print(f"PASS: board keygennew-sign-b q=0 (fresh key, root rebuilt from new SEED+I)")

    # 0x56 Verify: pubB verifies the sign-b (q=0) signature - self-consistent closed loop
    verify_request = (
        bytes((REQUEST_VERIFY,)) + pub_b
        + struct.pack(">H", len(msg)) + msg + sigb
    )
    original_timeout = port.timeout
    try:
        port.timeout = 60.0
        write_paced(port, verify_request, chunk_size=4, sleep_time=0.004)
        rv = read_exact(port, RESPONSE_SIZE)
    finally:
        port.timeout = original_timeout
    if rv[1] != 0:
        raise RuntimeError(f"keygennew-verify-b: status={rv[1]} hex={rv[:8].hex()}")
    print("PASS: board keygennew verify-b self-consistent (pubB x sigB q=0)")

    # Cleanup: reset the secure domain to factory state (repeatable)
    zero = bytes(64)
    sec_nvm_load(port, 0, zero)
    sec_nvm_load(port, 1, zero)
    sec_cmd(port, SEC_SUB_BOOT, _key_i(vector))
    print("PASS: board keygennew cleanup zero-slots (repeatable)")
    print("PASS: board multi-key rotation (0x68 KeyGen_NEW / new SEED / new I / q reset / self-consistent)")


def run_deploy_factory_phase(port: serial.Serial, vector: dict[str, str]) -> None:
    """P1-6 (0.1.274) deploy two-phase part A (test bit): FACTORY_INIT produces a wrapped blob
    -> fetch and save to build/deploy_blob.bin (host persistent domain; for deploy-bit push-back + BOOT unwrap)."""
    r = sec_cmd(port, SEC_SUB_FACTORY_INIT, _key_i(vector))
    if r[18] == 8:
        raise RuntimeError("factory already locked (reflash test bit first)")
    if r[18] != 0 or r[20] != 0x46:
        raise RuntimeError(f"deploy factory phase: status={r[18]} magic=0x{r[20]:02x}")
    blob = sec_wrapped_read(port)
    out = Path("build/deploy_blob.bin")
    out.write_bytes(blob)
    print(f"PASS: deploy-factory-phase wrapped blob {blob[:2].hex()}...{blob[-2:].hex()} -> {out}")


def run_deploy_board_cases(port: serial.Serial, vector: dict[str, str]) -> None:
    """P1-6 (0.1.274) deploy two-phase part B (deploy bit, INSECURE_TEST_MODE=0 + SEC_TEST=0):
    plaintext SEED_LOAD/FACTORY_INIT/INJECT_TAG rejected -> wrapped push-back -> BOOT unwrap restores SEED
    (plaintext never stored) -> 0x67/0x66/0x56 self-consistent closed loop (device-specific public key, correctness endorsed by signature verification)."""
    blob = Path("build/deploy_blob.bin").read_bytes()
    if len(blob) != 48:
        raise RuntimeError("build/deploy_blob.bin missing (run --deploy-factory phase A first)")

    # (1) Plaintext SEED_LOAD (0x63) rejected: frame[1]=1, frame[2]=RTL ERR_INSECURE_DISABLED=0x0a.
    write_paced(port, bytes((0x63,)) + b"\x21" * 32)
    r = read_exact(port, RESPONSE_SIZE)
    if r[1] != 1 or r[2] != 0x0A:
        raise RuntimeError(f"deploy seed-load: status={r[1]} hw_error=0x{r[2]:02x} (expect 1/0x0a)")
    print("PASS: deploy seed-load rejected hw_error=0x0a (plaintext SEED closed)")

    # (2) FACTORY_INIT / INJECT_TAG rejected (deploy firmware SEC_ERR_UNSUPPORTED=9).
    r = sec_cmd(port, SEC_SUB_FACTORY_INIT, _key_i(vector))
    if r[18] != 9:
        raise RuntimeError(f"deploy factory-init: status={r[18]} (expect 9)")
    print("PASS: deploy factory-init rejected status=9 (factory config only)")
    r = sec_cmd(port, SEC_SUB_INJECT_TAG)
    if r[18] != 9:
        raise RuntimeError(f"deploy inject-tag: status={r[18]} (expect 9)")
    print("PASS: deploy inject-tag rejected status=9")

    # (3) wrapped push-back -> BOOT -> IDLE ctr=0 (unwrap restores SEED, plaintext never stored).
    sec_wrap_load(port, blob)
    state, ctr = sec_boot(port, _key_i(vector))
    if state != 1 or ctr != 0:
        raise RuntimeError(f"deploy boot: state={state} ctr={ctr} (expect IDLE/0)")
    print("PASS: deploy boot unwrap OK state=IDLE ctr=0 key_loaded=1")

    # (4) 0x67 KeyGen -> device-specific public key; 0x66 Sign x2 -> q=0/1, ctr increasing; 0x56 self-consistent verification.
    status, pub, _, _ = sec_lms_keygen(port, vector)
    if status != 0:
        raise RuntimeError(f"deploy keygen: status={status}")
    print("PASS: deploy sec-lms-keygen pub produced (device-specific)")
    # Device KeyGen-generated I = public key [8:24] (PK=lmstype(4)||otstype(4)||I(16)||T1(32)),
    # sign request uses this device I (host records the public key to obtain I and sends it back for sign - consistent with keygen, not the vector I).
    device_i = pub[8:24]

    status, q0, sig0, _, _, _ = sec_lms_sign(port, vector, i_override=device_i)
    if status != 0 or q0 != 0:
        raise RuntimeError(f"deploy sign-1: status={status} q={q0}")
    _, ctr1, _ = sec_get_state(port)
    if ctr1 != 1:
        raise RuntimeError(f"deploy sign-1 post ctr={ctr1} (expect 1)")
    print("PASS: deploy sec-lms-sign-1 q=0 committed ctr=1 (Release=>Committed)")

    status, q1, _, _, _, _ = sec_lms_sign(port, vector, i_override=device_i)
    if status != 0 or q1 != 1:
        raise RuntimeError(f"deploy sign-2: status={status} q={q1}")
    print("PASS: deploy sec-lms-sign-2 q=1 strictly increasing")

    msg = bytes.fromhex(vector["MESSAGE"])
    verify_request = bytes((REQUEST_VERIFY,)) + pub + struct.pack(">H", len(msg)) + msg + sig0
    original_timeout = port.timeout
    try:
        port.timeout = 60.0
        write_paced(port, verify_request, chunk_size=4, sleep_time=0.004)
        rv = read_exact(port, RESPONSE_SIZE)
    finally:
        port.timeout = original_timeout
    if rv[1] != 0:
        raise RuntimeError(f"deploy verify: status={rv[1]} hex={rv[:8].hex()}")
    print("PASS: deploy verify self-consistent (0x67 pub x 0x66 sig)")

    # (5) (0.1.281 model B) 0x68 KEYGEN_NEW (deploy): new SEED+I generated on the fly by the **on-device TRNG**
    # (CMD_SEED_WRITE_SAFE controlled load into slot 0, plaintext SEED_LOAD gating remains) -> pubB!=pubA, ctr reset
    # -> Sign q=0 (new device I) -> Verify self-consistent (full multi-key-rotation deploy chain; host should persist the new blob).
    dummy_i = b"\x00" * 16   # deploy ignores i_new (device generates I)
    status, pub_b, _, _ = sec_lms_keygen_new(port, vector, dummy_i)
    if status != 0:
        raise RuntimeError(f"deploy keygen-new: status={status}")
    if pub_b == pub or len(pub_b) != len(pub):
        raise RuntimeError("deploy keygen-new: pubB == pubA (expected fresh on-device key)")
    print("PASS: deploy keygen-new status=0 pubB != pubA (on-device TRNG SEED+I)")
    _, ctr_b, _ = sec_get_state(port)
    if ctr_b != 0:
        raise RuntimeError(f"deploy keygen-new post ctr={ctr_b} (expect 0, fresh key)")
    print("PASS: deploy keygen-new post-rotate ctr=0 (fresh q)")
    status, qb0, sig_b, _, _, _ = sec_lms_sign(port, vector, i_override=pub_b[8:24])
    if status != 0 or qb0 != 0:
        raise RuntimeError(f"deploy keygen-new sign: status={status} q={qb0}")
    verify_request_b = bytes((REQUEST_VERIFY,)) + pub_b + struct.pack(">H", len(msg)) + msg + sig_b
    try:
        port.timeout = 60.0
        write_paced(port, verify_request_b, chunk_size=4, sleep_time=0.004)
        rvb = read_exact(port, RESPONSE_SIZE)
    finally:
        port.timeout = original_timeout
    if rvb[1] != 0:
        raise RuntimeError(f"deploy keygen-new verify: status={rvb[1]} hex={rvb[:8].hex()}")
    print("PASS: deploy keygen-new verify self-consistent (fresh key full chain)")
    print("PASS: board deploy-semantics closed loop (rejections + BOOT unwrap + 0x67/0x66/0x56 + 0x68 multi-key-rotation self-consistent)")


def read_exact(port: serial.Serial, size: int) -> bytes:
    data = bytearray()
    while len(data) < size:
        chunk = port.read(size - len(data))
        if not chunk:
            raise TimeoutError(f"UART timeout after {len(data)}/{size} response bytes")
        data.extend(chunk)
    return bytes(data)


def write_paced(
    port: serial.Serial, data: bytes, chunk_size: int = 16, sleep_time: float = 0.001
) -> None:
    for offset in range(0, len(data), chunk_size):
        port.write(data[offset : offset + chunk_size])
        port.flush()
        time.sleep(sleep_time)


def run_case(
    port: serial.Serial,
    name: str,
    message: bytes,
    expected_cycles: int,
    previous_hits: int | None,
) -> int:
    port.write(bytes((REQUEST_HASH, len(message))) + message)
    port.flush()
    response = read_exact(port, RESPONSE_SIZE)
    marker, status, hw_error, reserved, cycles, hits, fallback = struct.unpack_from("<BBBBIII", response)
    digest = response[16:48]
    expected_digest = _hash(message)

    if marker != RESPONSE or status != 0 or hw_error != 0 or reserved != 0:
        raise RuntimeError(
            f"{name}: marker=0x{marker:02x} status={status} hw_error={hw_error} reserved={reserved}"
        )
    hits_valid = hits >= 2 if previous_hits is None else hits == previous_hits + 1
    if cycles != expected_cycles or not hits_valid or fallback != 0:
        raise RuntimeError(
            f"{name}: cycles={cycles}/{expected_cycles} hits={hits} "
            f"previous_hits={previous_hits} fallback={fallback}"
        )
    if digest != expected_digest:
        raise RuntimeError(f"{name}: digest={digest.hex()} expected={expected_digest.hex()}")

    print(
        f"PASS: {name:<6} bytes={len(message):3d} cycles={cycles} "
        f"hits={hits} fallback={fallback} digest={digest.hex()}"
    )
    return hits


def run_chain_case(port: serial.Serial, previous_hits: int) -> int:
    identifier = bytes(range(16))
    value = bytes(range(32))
    q = 2
    index = 3
    start = 4
    steps = 5
    request = (
        bytes((REQUEST_CHAIN,))
        + identifier
        + struct.pack("<IHBB", q, index, start, steps)
        + value
    )
    write_paced(port, request)
    response = read_exact(port, RESPONSE_SIZE)
    marker, status, hw_error, reserved, cycles, hits, fallback = struct.unpack_from("<BBBBIII", response)
    digest = response[16:48]

    expected = _chain_expected(identifier, q, index, start, steps, value)

    if marker != RESPONSE or status != 0 or hw_error != 0 or reserved != 0:
        raise RuntimeError(
            f"chain: marker=0x{marker:02x} status={status} hw_error={hw_error} reserved={reserved}"
        )
    if cycles != EXPECTED[HASH_MODE]["chain"] or hits != previous_hits + 1 or fallback != 0:
        raise RuntimeError(
            f"chain: cycles={cycles}/{EXPECTED[HASH_MODE]['chain']} hits={hits} previous_hits={previous_hits} fallback={fallback}"
        )
    if digest != expected:
        raise RuntimeError(f"chain: digest={digest.hex()} expected={expected.hex()}")

    print(
        f"PASS: chain  start={start} steps={steps} cycles={cycles} "
        f"hits={hits} fallback={fallback} digest={digest.hex()}"
    )
    return hits


def load_verify_vector() -> dict[str, str]:
    global BIG_MSG
    fields = {}
    if VECTOR_OVERRIDE is not None:
        path = Path(VECTOR_OVERRIDE)
    else:
        # Pick the multi-parameter vector by hash flavor (2026-08-15 lesson): build/vectors/lms_verify_vector_*.txt
        # are SHA-256 parameter-scan artifacts; if a SHAKE board test mistakenly uses them -> type code mismatch -> whole batch falsely fails
        # (root cause of the 0.1.269 SHAKE "batch failure" misdiagnosis). SHAKE256 prefers files with the shake_ prefix.
        if HASH_MODE == "shake256":
            path = Path(f"build/vectors/shake_lms_verify_vector_W{W}_H{H}.txt")
            if not path.exists():
                path = Path(f"build/vectors/lms_verify_vector_W{W}_H{H}.txt")
        else:
            path = Path(f"build/vectors/lms_verify_vector_W{W}_H{H}.txt")
        if not path.exists():
            path = VERIFY_VECTOR  # default W4/H5 fallback (build/lms_verify_vector.txt)
    for line in path.read_text(encoding="ascii").splitlines():
        name, value = line.split("=", 1)
        fields[name] = value
    # Fixed-length field checks; signature length follows the parameter set (not the 2348/2180 W4/H5 special case), no CALLS special-case check.
    if (
        len(bytes.fromhex(fields["PRIVATE_KEY"])) != 60
        or len(bytes.fromhex(fields["PUBLIC_KEY"])) != 56
        or len(bytes.fromhex(fields["MESSAGE"])) > 2048
        or len(bytes.fromhex(fields["LMOTS_PUBLIC_KEY"])) != 32
    ):
        raise RuntimeError(f"invalid LMS Verify vector ({path.name})")
    # Large message: >74B message hash goes through HASH_ONCE_RAM (multi-block), LM-OTS/LMS hw cycles include multi-block
    # absorb ticks (e.g. 1KB lmots_sign 6879 vs 19B 6414) -> expected hw relaxed (correctness checked byte by byte).
    BIG_MSG = len(bytes.fromhex(fields["MESSAGE"])) > 74
    # Vector hash-flavor guard (2026-08-15 lesson): build/lms_verify_vector.txt is regenerated per HASH_IMPL
    # (FORCE); if regeneration is forgotten after switching platforms, the vector still has the old platform's type codes (SHA-256 h/ots=
    # 5/3, SHAKE256 21/19), the board firmware directly INVALIDates signatures of the wrong type -> whole batch falsely fails
    # (root cause of the 0.1.269 SHAKE board-test "batch failure" misdiagnosis). In pure-software builds (NO_HW_ACCEL) the firmware
    # contains both hash suites and verifies either vector, so the guard is skipped.
    if not PURE_SW:
        exp_lms = {(5, "sha256"): 5, (10, "sha256"): 6, (15, "sha256"): 7,
                   (5, "shake256"): 21, (10, "shake256"): 22, (15, "shake256"): 23}
        exp_ots = {(1, "sha256"): 1, (2, "sha256"): 2, (4, "sha256"): 3, (8, "sha256"): 4,
                   (1, "shake256"): 17, (2, "shake256"): 18, (4, "shake256"): 19, (8, "shake256"): 20}
        h_val = int(fields["PRIVATE_KEY"][:8], 16)
        ots_val = int(fields["PRIVATE_KEY"][8:16], 16)
        if h_val != exp_lms[(H, HASH_MODE)] or ots_val != exp_ots[(W, HASH_MODE)]:
            raise RuntimeError(
                f"vector hash-flavor mismatch ({path.name}): PRIVATE_KEY h/ots="
                f"0x{h_val:08x}/0x{ots_val:08x} but --hash={HASH_MODE} --w={W} --h={H} "
                f"expects 0x{exp_lms[(H, HASH_MODE)]:08x}/0x{exp_ots[(W, HASH_MODE)]:08x}; "
                f"regenerate with: make build/lms_verify_vector.txt HASH_IMPL={HASH_MODE}"
            )
    return fields


def expected_hw_cycles(op: str) -> int | None:
    """Hardware expected cycles for the current parameter set. W4 uses a lookup table (H5 measured values); w!=4 also uses hardware
    on both platforms (SHAKE256 stage 3 / SHA-256 S5 engine parameterized for all w) -> return None (hw>0 but values differ per w,
    only the actual value is printed, not compared; correctness is guaranteed by byte-by-byte comparison). w!=4 LMS triple D_INTR tree-hash
    hw varies with h -> return None. W4+H10/H15 LMS triple hw differs from H5 -> return None."""
    if BIG_MSG:
        return None  # large message: message hash HASH_ONCE_RAM changes hw, only print the actual value
    if PURE_SW:
        if op.startswith("lms_"):
            return None
        return 0
    if W != 4:
        return None  # all-w hardware (both platforms): LM-OTS/LMS values vary with w/h, byte-by-byte comparison guarantees correctness
    if H != 5 and op in ("lms_verify", "lms_keygen", "lms_sign"):
        return None
    # DERIVE_SHUFFLE=1 build (--shuffle / LMS_KAT_SKIP_CYCLES=1): batch tasks get random start shifts that
    # offset DERIVE-segment cycle counts (measured verify +48, sign ±9% variation) - cycle assertions do not apply,
    # correctness is guaranteed by byte-by-byte comparison.
    if SHUFFLE or os.environ.get("LMS_KAT_SKIP_CYCLES"):
        return None
    return EXPECTED[HASH_MODE][op]


def expected_hits_inc(op: str) -> int:
    """Hardware hits increment for the current parameter set. Pure software -> 0; hardware available for w!=4 on both platforms (SHAKE256 stage 3 /
    SHA-256 S5) -> LM-OTS increment from lookup table (fused keygen/sign/verify hits, independent of h);
    LMS layer for w!=4 -> 0 (D_INTR/message-hash hits vary with w/h, pending measurement).
    W4 LM-OTS layer hits depend only on w (fused keygen/sign/verify, independent of h) -> lookup table; W4 LMS
    layer uses the H5 lookup, W4+non-H5 -> 0 (hits pending measurement, correctness guaranteed by byte-by-byte signature/public-key comparison)."""
    if PURE_SW:
        return 0
    if W != 4:
        if op.startswith("lmots_"):
            return EXPECTED[HASH_MODE][op + "_hits"]  # hardware fused-backend hits (independent of h)
        return 0
    if op.startswith("lmots_"):
        return EXPECTED[HASH_MODE][op + "_hits"]  # LM-OTS hits are independent of h
    if H != 5:
        return 0
    return EXPECTED[HASH_MODE][op + "_hits"]


def run_verify_case(port: serial.Serial, previous_hits: int, timeout: float = 60.0) -> int:
    vector = load_verify_vector()
    public_key = bytes.fromhex(vector["PUBLIC_KEY"])
    message = bytes.fromhex(vector["MESSAGE"])
    signature = bytes.fromhex(vector["SIGNATURE"])
    calls = int(vector["CALLS"])
    steps = int(vector["STEPS"])
    request = bytearray((REQUEST_VERIFY,))
    request += public_key
    request += struct.pack(">H", len(message)) + message
    # Level 1 (>74B): message padded to 4B alignment (firmware bridge passes through ceil(m/4)*4 bytes)
    if len(message) > 74:
        request += b"\x00" * ((4 - len(message) % 4) % 4)
    request += signature
    # verify long frames (W1 8684B) drop bytes under the firmware layout at the default 16B/1ms pacing
    # (RV32 no-icache layout-sensitive + uart_rx depth-2 FIFO), slow down to 4B/4ms for stability.
    write_paced(port, bytes(request), chunk_size=4, sleep_time=0.004)
    # Response timeout must cover firmware software leaf verification: w=8 pure software 34 chains x 255 steps ~ 3.4e8 cycles ~ 7s
    # (default port.timeout=3s is not enough), w!=4 uniformly uses --verify-timeout (default 60s).
    original_timeout = port.timeout
    try:
        port.timeout = timeout
        response = read_exact(port, RESPONSE_SIZE)
    finally:
        port.timeout = original_timeout
    marker, status, hw_error, reserved, cycles, hits, fallback = struct.unpack_from("<BBBBIII", response)
    # End-to-end total time (SOC_CYCLE_COUNT delta, includes software orchestration + hashing), frame[20..23].
    total_cycles = struct.unpack_from("<I", response, 20)[0]
    expected_cycles = expected_hw_cycles("lms_verify")
    expected_hits = previous_hits + expected_hits_inc("lms_verify")

    if marker != RESPONSE or status != 0 or hw_error != 0 or reserved != 0:
        raise RuntimeError(
            f"verify: marker=0x{marker:02x} status={status} hw_error={hw_error} "
            f"reserved={reserved} cycles={cycles} hits={hits} fallback={fallback}"
        )
    if expected_cycles is not None and (
        cycles != expected_cycles or hits != expected_hits or fallback != 0
    ):
        raise RuntimeError(
            f"verify: cycles={cycles}/{expected_cycles} hits={hits}/{expected_hits} fallback={fallback}"
        )
    if expected_cycles is None and fallback != 0:
        raise RuntimeError(f"verify: fallback={fallback}")
    # frame[16..19]=response_value(0), [20..23]=total_cycles, [24..47] should be 0.
    if any(response[16:20]) or any(response[24:48]):
        raise RuntimeError(f"verify: expected zero payload, got {response[16:48].hex()}")

    sw_overhead = total_cycles - cycles  # software orchestration/tree-hash overhead (end-to-end - hardware compressed ticks)
    print(
        f"PASS: verify calls={calls} steps={steps} hw_cycles={cycles} "
        f"total_cycles={total_cycles} sw_overhead={sw_overhead} hits={hits} fallback={fallback}"
    )
    return hits


def run_sign_test_case(port: serial.Serial, previous_hits: int, timeout: float) -> int:
    """INSECURE_TEST_MODE: transmit a plaintext private key for board-only KAT testing."""
    vector = load_verify_vector()
    private_key = bytes.fromhex(vector["PRIVATE_KEY"])
    message = bytes.fromhex(vector["MESSAGE"])
    expected_signature = bytes.fromhex(vector["SIGNATURE"])
    # After tree caching is enabled (fw 0.1.171 step 6b): H5 registers the lms_subtree backend, the auth path goes through
    # software cache lookup (hit = zero hardware calls), Sign hardware cycles/hits are only the LM-OTS signature itself
    # (LMOTS_SIGN_*), no longer the FULL_SIGN_* recursive auth-path rebuild; sign_init tree building has
    # KeyGen semantics and is not counted in Sign statistics. The signature is still compared byte by byte with the vector.
    calls = int(vector["LMOTS_SIGN_CALLS"])
    steps = int(vector["LMOTS_SIGN_STEPS"])
    request = bytearray((REQUEST_SIGN_TEST,))
    request += private_key
    request += struct.pack(">H", len(message)) + message
    # Level 1 (>74B): message padded to 4B alignment (firmware bridge passes through ceil(m/4)*4 bytes)
    if len(message) > 74:
        request += b"\x00" * ((4 - len(message) % 4) % 4)

    original_timeout = port.timeout
    wall_start = time.monotonic()
    try:
        port.timeout = timeout
        write_paced(port, request)
        response = read_exact(port, RESPONSE_SIZE)
        signature = read_exact(port, len(expected_signature))
        wall_elapsed = time.monotonic() - wall_start
    finally:
        port.timeout = original_timeout

    marker, status, hw_error, reserved, cycles, hits, fallback = struct.unpack_from(
        "<BBBBIII", response
    )
    next_q = struct.unpack_from("<I", response, 16)[0]
    total_cycles = struct.unpack_from("<I", response, 20)[0]
    steady_total = struct.unpack_from("<I", response, 24)[0]
    parse_cycles = struct.unpack_from("<I", response, 28)[0]
    # 32-bit SOC_CYCLE_COUNT wrap recovery (2026-08-23 addendum): no-cache pure-software Sign rebuilds the whole tree
    # (W4_H10 ~42.9B cycles) exceeding 2^32 wraps; the wrap constant uses the physical PLL clock actually on the
    # board (15.625MHz, TVLA bit). Measured cycle counts are clock-frequency independent, so they match the paper's
    # 50 MHz performance scope; only wrap recovery needs the physical clock.
    total_resid = total_cycles
    wraps = round((wall_elapsed * 15_625_000.0 - total_resid) / 4294967296.0)
    if wraps > 0:
        total_cycles = total_resid + wraps * 4294967296
    wrap_note = f" resid={total_resid}+{wraps}x2^32" if wraps > 0 else ""
    expected_cycles = expected_hw_cycles("lms_sign")
    expected_hits = previous_hits + expected_hits_inc("lms_sign")
    if marker != RESPONSE or status != 0 or hw_error != 0 or reserved != 0:
        raise RuntimeError(
            f"sign: marker=0x{marker:02x} status={status} hw_error={hw_error} "
            f"reserved={reserved} cycles={cycles} hits={hits} fallback={fallback} q={next_q}"
        )
    if next_q != 1:
        raise RuntimeError(f"sign: q={next_q}/1")
    if expected_cycles is not None and (
        cycles != expected_cycles or hits != expected_hits or fallback != 0
    ):
        raise RuntimeError(
            f"sign: cycles={cycles}/{expected_cycles} hits={hits}/{expected_hits} "
            f"fallback={fallback}"
        )
    if expected_cycles is None and fallback != 0:
        raise RuntimeError(f"sign: fallback={fallback}")
    if any(response[44:48]) or signature != expected_signature:
        n = min(len(signature), len(expected_signature))
        fb = next((i for i in range(n) if signature[i] != expected_signature[i]), n)
        lo = max(0, fb - 8)
        hi = min(len(signature), fb + 8)
        print(f"SIGN DIAG: rx={len(signature)} exp={len(expected_signature)} first_bad={fb} (y off {max(0, fb - 44)})")
        print(f"SIGN DIAG: got={signature[lo:hi].hex()}")
        print(f"SIGN DIAG: exp={expected_signature[lo:hi].hex()}")
        # whether the first 8 bytes of each chain are correct (y segment starts at 40, W4 32B per chain): locate the "first 2 words per chain correct" pattern
        ybase = 40
        for k in range(4):
            off = k * 32
            if ybase + off + 8 <= n:
                ok = signature[ybase + off:ybase + off + 8] == expected_signature[ybase + off:ybase + off + 8]
                print(f"SIGN DIAG: y[{off}..{off+7}] match={ok} got={signature[ybase+off:ybase+off+8].hex()}")
        raise RuntimeError("sign: response padding or signature differs from the software vector")

    if any(response[32:48]) or signature != expected_signature:
        raise RuntimeError("sign: response padding or signature differs from the software vector")

    sw_overhead = total_cycles - cycles  # software orchestration/tree-hash overhead (end-to-end - hardware compressed ticks)
    print(
        f"PASS: sign(cached) calls={calls} steps={steps} hw_cycles={cycles} "
        f"total_cycles={total_cycles}{wrap_note} steady_total={steady_total} sw_overhead={sw_overhead} "
        f"hits={hits} fallback={fallback} q={next_q} parse={parse_cycles}"
    )
    return hits


def run_keygen_test_case(port: serial.Serial, previous_hits: int, timeout: float) -> int:
    """INSECURE_TEST_MODE: transmit a plaintext private key for board-only KAT testing."""
    vector = load_verify_vector()
    private_key = bytes.fromhex(vector["PRIVATE_KEY"])
    expected_public_key = bytes.fromhex(vector["PUBLIC_KEY"])
    calls = int(vector["KEYGEN_CALLS"])
    steps = int(vector["KEYGEN_STEPS"])

    original_timeout = port.timeout
    wall_start = time.monotonic()
    try:
        port.timeout = timeout
        write_paced(port, bytes((REQUEST_KEYGEN_TEST,)) + private_key)
        response = read_exact(port, RESPONSE_SIZE)
        public_key = read_exact(port, len(expected_public_key))
        wall_elapsed = time.monotonic() - wall_start
    finally:
        port.timeout = original_timeout

    marker, status, hw_error, reserved, cycles, hits, fallback = struct.unpack_from(
        "<BBBBIII", response
    )
    total_cycles = struct.unpack_from("<I", response, 20)[0]
    # 32-bit SOC_CYCLE_COUNT wrap recovery (0.1.268 data fix): when keygen wall time exceeds the counter
    # wrap period (2^32 / 15.625MHz = 274.9s), total_cycles is the mod 2^32 residue; the wall-clock delta
    # recovers the wrap count k (wall-clock error << 2^32 ticks, so k is reliable).
    # ★ 2026-08-23 fix: clock constant 50MHz -> 15.625MHz (0.1.280 pure-software measurement of the actual clock,
    #   CW305 runs at half rate of the TVLA PLL 31.25MHz; the old 50MHz assumption overestimated wraps 3.2x,
    #   H5 KeyGen 1.34B wrongly got +1 wrap, H10 42.9B was miscalculated as 137.5B).
    total_resid = total_cycles
    wraps = round((wall_elapsed * 15_625_000.0 - total_resid) / 4294967296.0)
    if wraps > 0:
        total_cycles = total_resid + wraps * 4294967296
    expected_cycles = expected_hw_cycles("lms_keygen")
    expected_hits = previous_hits + expected_hits_inc("lms_keygen")
    if marker != RESPONSE or status != 0 or hw_error != 0 or reserved != 0:
        raise RuntimeError(
            f"keygen: marker=0x{marker:02x} status={status} hw_error={hw_error} "
            f"reserved={reserved} cycles={cycles} hits={hits} fallback={fallback}"
        )
    # Tree-cache hit (second KeyGen with the same key, 1KB/19B vectors share I/seed): tree build already cached -> hw=0,
    # hits only +1 (seed_load). Public key matching means correct (root taken from cache, KeyGen semantics with zero hardware recompute).
    # Legitimate when the board test runs multiple vectors in sequence; the first KeyGen after reset does the hardware tree build (strict assertion).
    cache_hit = cycles == 0 and hits == previous_hits + 1
    if expected_cycles is not None and not cache_hit and (
        cycles != expected_cycles or hits != expected_hits or fallback != 0
    ):
        raise RuntimeError(
            f"keygen: cycles={cycles}/{expected_cycles} hits={hits}/{expected_hits} "
            f"fallback={fallback}"
        )
    if expected_cycles is None and fallback != 0:
        raise RuntimeError(f"keygen: fallback={fallback}")
    if any(response[16:20]) or public_key != expected_public_key:
        raise RuntimeError("keygen: response padding or public key differs from software vector")

    sw_overhead = total_cycles - cycles  # software orchestration/tree-hash overhead (end-to-end - hardware compressed ticks)
    wrap_note = f" resid={total_resid}+{wraps}x2^32" if wraps > 0 else ""
    print(
        f"PASS: keygen calls={calls} steps={steps} hw_cycles={cycles} "
        f"total_cycles={total_cycles}{wrap_note} sw_overhead={sw_overhead} hits={hits} "
        f"fallback={fallback} wall={wall_elapsed:.2f}s"
    )
    return hits


def run_lmots_test_cases(port: serial.Serial, previous_hits: int, timeout: float) -> int:
    """INSECURE_TEST_MODE: run direct LM-OTS KeyGen, Sign, and Verify on the board."""
    vector = load_verify_vector()
    private_key = bytes.fromhex(vector["PRIVATE_KEY"])
    message = bytes.fromhex(vector["MESSAGE"])
    public_key = bytes.fromhex(vector["LMOTS_PUBLIC_KEY"])
    signature = bytes.fromhex(vector["LMOTS_SIGNATURE"])

    original_timeout = port.timeout
    try:
        port.timeout = timeout
        write_paced(port, bytes((REQUEST_LMOTS_KEYGEN_TEST,)) + private_key)
        response = read_exact(port, RESPONSE_SIZE)
        actual_public_key = read_exact(port, len(public_key))
        calls = int(vector["LMOTS_KEYGEN_CALLS"])
        steps = int(vector["LMOTS_KEYGEN_STEPS"])
        expected_cycles = expected_hw_cycles("lmots_keygen")  # fused LMOTS_KEYGEN (dual-core)
        expected_hit_increment = expected_hits_inc("lmots_keygen")
        previous_hits, total_cycles, parse_cycles, sign_cycles = check_lmots_response(
            "lmots-keygen", response, previous_hits, expected_cycles, expected_hit_increment
        )
        if actual_public_key != public_key:
            raise RuntimeError("lmots-keygen: public key differs from software vector")
        actual_cycles = struct.unpack_from("<I", response, 4)[0]  # hw (show actual value when expectation is None)
        print(f"PASS: lmots-keygen calls={calls} steps={steps} hw_cycles={actual_cycles} total_cycles={total_cycles} sw_overhead={total_cycles-actual_cycles} hits={previous_hits} fallback=0")

        request = bytes((REQUEST_LMOTS_SIGN_TEST,)) + private_key + struct.pack(">H", len(message)) + message
        write_paced(port, request)
        response = read_exact(port, RESPONSE_SIZE)
        try:
            actual_signature = read_exact(port, len(signature))
        except TimeoutError:
            # Diagnostics (known bug: after running the LMS triple, w!=4 0x71 signatures are 0 bytes):
            # dump the response frame to distinguish parse failure (status=1, sig_len=0) vs hardware error (hw_error!=0).
            marker, status, hw_error, reserved, cycles, hits, fallback = struct.unpack_from(
                "<BBBBIII", response
            )
            total_cycles = struct.unpack_from("<I", response, 20)[0]
            parse_cycles = struct.unpack_from("<I", response, 24)[0]
            sign_cycles = struct.unpack_from("<I", response, 28)[0]
            print(
                f"LMOTS-SIGN TIMEOUT DIAG: response={response.hex()} marker={marker:#04x} "
                f"status={status} hw_error={hw_error} reserved={reserved} cycles={cycles} "
                f"hits={hits} fallback={fallback} total={total_cycles} parse={parse_cycles} "
                f"sign_internal={sign_cycles} expect_sig_len={len(signature)}"
            )
            raise
        calls = int(vector["LMOTS_SIGN_CALLS"])
        steps = int(vector["LMOTS_SIGN_STEPS"])
        expected_cycles = expected_hw_cycles("lmots_sign")  # dual-core DERIVE + CHAIN
        expected_hit_increment = expected_hits_inc("lmots_sign")  # 1 randomizer derive + 1 fused sign
        previous_hits, total_cycles, parse_cycles, sign_cycles = check_lmots_response(
            "lmots-sign", response, previous_hits, expected_cycles, expected_hit_increment
        )
        if actual_signature != signature:
            first_bad = next(
                (i for i in range(min(len(actual_signature), len(signature)))
                 if actual_signature[i] != signature[i]),
                min(len(actual_signature), len(signature)))
            print(f"  DIAG sign len got={len(actual_signature)} exp={len(signature)} first_bad={first_bad}")
            if first_bad < min(len(actual_signature), len(signature)):
                print(f"  DIAG got[{first_bad}:{first_bad+8}]={actual_signature[first_bad:first_bad+8].hex()}")
                print(f"  DIAG exp[{first_bad}:{first_bad+8}]={signature[first_bad:first_bad+8].hex()}")
                # C segment = bytes 4..36 (after the 4B type); y segment starts at 36. Check whether C matches.
                print(f"  DIAG C got={actual_signature[4:36].hex()}")
                print(f"  DIAG C exp={signature[4:36].hex()}")
                print(f"  DIAG y0 got={actual_signature[36:44].hex()} exp={signature[36:44].hex()}")
            raise RuntimeError("lmots-sign: signature differs from software vector")
        # frame[32..35]=steady_total (steady single signature after seed_load, same basis as LMS Sign steady).
        steady_total = struct.unpack_from("<I", response, 32)[0]
        if steady_total >= total_cycles:
            raise RuntimeError(
                f"lmots-sign: steady_total={steady_total} >= total={total_cycles} (semantics anomaly)"
            )
        actual_sign_hw = struct.unpack_from("<I", response, 4)[0]  # hw (show actual value when expectation is None)
        sw_overhead = sign_cycles - actual_sign_hw
        print(f"PASS: lmots-sign   calls={calls} steps={steps} hw_cycles={actual_sign_hw} total_cycles={total_cycles} steady_total={steady_total} hits={previous_hits} fallback=0")
        print(f"      profile: parse={parse_cycles} sign_internal={sign_cycles} sw_overhead={sw_overhead} (hw={actual_sign_hw})")

        request = (
            bytes((REQUEST_LMOTS_VERIFY_TEST,))
            + private_key[8:24]
            + struct.pack("<I", 0)
            + public_key
            + struct.pack(">H", len(message))
            + message
            + signature
        )
        write_paced(port, request)
        response = read_exact(port, RESPONSE_SIZE)
        calls = int(vector["CALLS"])
        steps = int(vector["STEPS"])
        expected_cycles = expected_hw_cycles("lmots_verify")  # dual-core Verify CHAIN
        previous_hits, total_cycles, parse_cycles, sign_cycles = check_lmots_response(
            "lmots-verify", response, previous_hits, expected_cycles,
            expected_hits_inc("lmots_verify")
        )
        actual_verify_cycles = struct.unpack_from("<I", response, 4)[0]  # hw (show actual value when expectation is None)
        print(f"PASS: lmots-verify calls=1 steps={steps} hw_cycles={actual_verify_cycles} total_cycles={total_cycles} sw_overhead={total_cycles-actual_verify_cycles} hits={previous_hits} fallback=0")
    finally:
        port.timeout = original_timeout
    return previous_hits


def check_lmots_response(
    name: str,
    response: bytes,
    previous_hits: int,
    expected_cycles: int,
    expected_hit_increment: int,
) -> tuple[int, int, int, int]:
    """Returns (hits, total_cycles, parse_cycles, sign_cycles).

    parse_cycles = lms_private_key_parse elapsed time (frame[24..27]).
    sign_cycles = lmots_sign internal elapsed time (frame[28..31]), includes 69xSHA-256 + hardware chain + memcpy.
    """
    marker, status, hw_error, reserved, cycles, hits, fallback = struct.unpack_from(
        "<BBBBIII", response
    )
    total_cycles = struct.unpack_from("<I", response, 20)[0]
    parse_cycles = struct.unpack_from("<I", response, 24)[0]
    sign_cycles = struct.unpack_from("<I", response, 28)[0]
    expected_hits = previous_hits + expected_hit_increment
    if marker != RESPONSE or status != 0 or hw_error != 0 or reserved != 0:
        raise RuntimeError(
            f"{name}: marker=0x{marker:02x} status={status} hw_error={hw_error} reserved={reserved}"
        )
    if expected_cycles is not None and (
        cycles != expected_cycles or hits != expected_hits or fallback != 0 or any(response[16:20])
    ):
        raise RuntimeError(
            f"{name}: cycles={cycles}/{expected_cycles} hits={hits}/{expected_hits} fallback={fallback}"
        )
    if expected_cycles is None and (
        hits != expected_hits or fallback != 0 or any(response[16:20])
    ):
        raise RuntimeError(
            f"{name}: cycles={cycles} hits={hits}/{expected_hits} fallback={fallback}"
        )
    return hits, total_cycles, parse_cycles, sign_cycles


def main() -> int:
    parser = argparse.ArgumentParser(description="Run LMS HASH_ONCE KATs over the DaVinci Pro UART")
    parser.add_argument("--port", default="COM5")
    parser.add_argument("--baud", type=int, default=115200)
    parser.add_argument(
        "--transport",
        choices=["serial", "cw305"],
        default="serial",
        help="serial backend: serial=pyserial COM port (DaVinci Pro, default); "
        "cw305=ChipWhisperer register mailbox (CW305, requires lms_cw305.bit flashed, ignores --port/--baud)",
    )
    parser.add_argument("--timeout", type=float, default=3.0)
    parser.add_argument(
        "--hash",
        choices=["sha256", "shake256"],
        default="sha256",
        help="hash under test (affects the digest oracle and expected cycles; default sha256)",
    )
    parser.add_argument(
        "--pure-software",
        action="store_true",
        help="pure-software baseline firmware (LMS_FW_NO_HW_ACCEL): LM-OTS/LMS expected hw=0, hits do not increase",
    )
    parser.add_argument(
        "--shuffle",
        action="store_true",
        help="DERIVE_SHUFFLE=1 build (TVLA variant): batch tasks get random start shifts that offset DERIVE-segment cycle "
        "counts (verify +48, sign ±9%%) -> skip precise cycle assertions (correctness still checked byte by byte; "
        "equivalent to env var LMS_KAT_SKIP_CYCLES=1)",
    )
    parser.add_argument(
        "--w",
        type=int,
        default=4,
        choices=[1, 2, 4, 8],
        help="LM-OTS Winternitz w (multi-parameter set, default 4). w!=4 has no hardware acceleration (pure software, hw=0)",
    )
    parser.add_argument(
        "--h",
        type=int,
        default=5,
        choices=[5, 10, 15],
        help="LMS tree height h (multi-parameter set, default 5)",
    )
    parser.add_argument(
        "--insecure-lmots-test",
        action="store_true",
        help="INSECURE_TEST_MODE: run direct LM-OTS KeyGen/Sign/Verify with a plaintext key",
    )
    parser.add_argument(
        "--insecure-keygen-test",
        action="store_true",
        help="INSECURE_TEST_MODE: send the fixed plaintext private key and run LMS KeyGen",
    )
    parser.add_argument(
        "--insecure-sign-test",
        action="store_true",
        help="INSECURE_TEST_MODE: send the fixed plaintext private key and run LMS Sign",
    )
    parser.add_argument("--sign-timeout", type=float, default=30.0)
    parser.add_argument("--keygen-timeout", type=float, default=30.0)
    parser.add_argument("--lmots-timeout", type=float, default=30.0)
    parser.add_argument("--verify-timeout", type=float, default=60.0, help="LMS Verify response timeout (w!=4 software leaf verification W8 needs ~7s, default 60s)")
    parser.add_argument(
        "--vector",
        default=None,
        help="specify the LMS Verify vector file (default picks build/vectors/ by W/H; e.g. 1KB large-message vector)",
    )
    parser.add_argument(
        "--nvm-sync-test",
        action="store_true",
        help="push build/nvm_state.bin back into the firmware NVM slot and read back to verify (stage-3 NVM sync)",
    )
    parser.add_argument(
        "--sec-board-test",
        action="store_true",
        help="on-board secure-domain closed loop: FACTORY_INIT/BOOT/SEC_SIGN q increment/half-write/rollback/exhaust/verify-stateless (spec §13 board-testable items; no key_handle, bad_handle not applicable)",
    )
    parser.add_argument(
        "--sec-lms-test",
        action="store_true",
        help="secured LMS triple (full security-scheme semantics): 0x67 SEC KeyGen (SEC-slot SEED builds tree and produces root) + 0x66 SEC Sign (sec_sign state machine + auth path) + Verify, quantifies the security cost",
    )
    parser.add_argument(
        "--sec-lms-keygen-new-test",
        action="store_true",
        help="multi-key rotation (test semantics): 0x67 KeyGen (pubA=vector) -> sign q=0 -> swap to new SEED+new I -> 0x68 KeyGen_NEW (pubB!=pubA, q reset) -> sign q=0 (using pubB's I) -> Verify self-consistent closed loop",
    )
    parser.add_argument(
        "--deploy-factory",
        action="store_true",
        help="P1-6 deploy two-phase A (test bit): FACTORY_INIT produces a wrapped blob saved to build/deploy_blob.bin",
    )
    parser.add_argument(
        "--deploy-test",
        action="store_true",
        help="P1-6 deploy two-phase B (deploy bit): SEED_LOAD/FACTORY_INIT/INJECT_TAG rejected + BOOT unwrap + 0x67/0x66/0x56 self-consistent closed loop",
    )
    args = parser.parse_args()

    global HASH_MODE, PURE_SW, W, H, VECTOR_OVERRIDE, SHUFFLE
    HASH_MODE = args.hash
    PURE_SW = args.pure_software
    SHUFFLE = args.shuffle
    W, H = args.w, args.h
    VECTOR_OVERRIDE = args.vector
    once = EXPECTED[HASH_MODE]["once"]
    cases = [
        ("empty", b"", once[0]),
        ("abc", b"abc", once[3]),
        ("seq55", bytes(range(55)), once[55]),
        ("seq64", bytes(range(64)), once[64]),
        ("seq128", bytes(range(128)), once[128]),
    ]

    if args.transport == "cw305":
        sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "scripts"))
        from cw305_serial import Cw305Serial  # type: ignore

        port_ctx = Cw305Serial(
            timeout=args.timeout, write_timeout=args.timeout
        )
    else:
        port_ctx = serial.Serial(
            args.port, args.baud, timeout=args.timeout, write_timeout=args.timeout
        )

    with port_ctx as port:
        port.reset_input_buffer()
        port.reset_output_buffer()
        time.sleep(0.05)
        # Thoroughly flush response bytes possibly left on the UART line by a previous abnormal exit (especially the verify 2348B
        # long frame): read out all pending bytes with a short timeout to avoid first-frame misalignment.
        port.timeout = 0.2
        while port.read(4096):
            pass
        port.timeout = args.timeout
        port.reset_input_buffer()

        # The secure-domain closed loop runs independently: if the FPGA was not reset, hits have already accumulated,
        # and the base KAT's previous_hits chained assertions would fail; sec-board cases rebuild the FACTORY_INIT/BOOT state
        # themselves and are independent of hits, so base KATs are skipped and the secure-domain loop runs directly.
        if args.sec_board_test:
            run_sec_board_cases(port, load_verify_vector())
            print("LMS DaVinci Pro UART SEC-BOARD KATs passed")
            return 0
        if args.sec_lms_test:
            run_sec_lms_cases(port, load_verify_vector())
            print("LMS DaVinci Pro UART SEC-LMS KATs passed")
            return 0
        if args.sec_lms_keygen_new_test:
            run_sec_lms_keygen_new_cases(port, load_verify_vector())
            print("LMS DaVinci Pro UART SEC-LMS-KEYGEN-NEW KATs passed")
            return 0
        if args.deploy_factory:
            run_deploy_factory_phase(port, load_verify_vector())
            print("LMS DaVinci Pro UART DEPLOY FACTORY phase A passed")
            return 0
        if args.deploy_test:
            run_deploy_board_cases(port, load_verify_vector())
            print("LMS DaVinci Pro UART DEPLOY-BOARD KATs passed")
            return 0

        previous_hits = None
        for name, message, cycles in cases:
            previous_hits = run_case(port, name, message, cycles, previous_hits)
        previous_hits = run_chain_case(port, previous_hits)
        if args.insecure_lmots_test:
            previous_hits = run_lmots_test_cases(port, previous_hits, args.lmots_timeout)
        # LMS triple in the same order as OTS: KeyGen -> Sign -> Verify (stateless Verify side effects last)
        if args.insecure_keygen_test:
            previous_hits = run_keygen_test_case(port, previous_hits, args.keygen_timeout)
        if args.insecure_sign_test:
            previous_hits = run_sign_test_case(port, previous_hits, args.sign_timeout)
        previous_hits = run_verify_case(port, previous_hits, args.verify_timeout)
        if args.nvm_sync_test:
            run_nvm_sync_case(port)

    suffix = "/LMOTS_TEST" if args.insecure_lmots_test else ""
    if args.insecure_keygen_test:
        suffix += "/KEYGEN_TEST"
    if args.insecure_sign_test:
        suffix += "/SIGN_TEST"
    print(f"LMS DaVinci Pro UART HASH_ONCE/CHAIN/VERIFY{suffix} KATs passed")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except (OSError, RuntimeError, TimeoutError, serial.SerialException) as error:
        print(f"FAIL: {error}", file=sys.stderr)
        sys.exit(1)
